name: Deploy to HostGator VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            set -e

            echo "===== INICIO ====="

            cd /opt/hello-word/mini_carteira_financeira

            echo "===== DIRETORIO ====="
            pwd

            echo "===== COMMIT ATUAL ====="
            git log -1 --oneline

            echo "===== BRANCH ====="
            git branch --show-current

            echo "===== REMOTE ====="
            git remote -v

            echo "===== FETCH ====="
            git fetch origin master

            echo "===== RESET PARA O GITHUB ====="
            git reset --hard origin/master

            echo "===== NOVO COMMIT ====="
            git log -1 --oneline

            echo "===== DOCKER DOWN ====="
            docker compose down

            echo "===== DOCKER BUILD E UP ====="
            docker compose up -d --build

            echo "===== STATUS FINAL ====="
            docker compose ps

            echo "===== DEPLOY FINALIZADO ====="