name: Deploy to HostGator VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /opt/hello-word/mini_carteira_financeira

            echo "Commit antes do pull:"
            git log -1 --oneline

            git pull origin master

            echo "Commit depois do pull:"
            git log -1 --oneline

            docker compose down
            docker compose up -d --build

            docker compose ps